# Generated by Django 5.0.2 on 2024-02-18 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('runtime', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='machine.machine')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='machine_runtime_date_idx'), models.Index(fields=['machine'], name='machine_idx')],
                'unique_together': {('machine', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vibration', models.FloatField()),
                ('date', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='machine.machine')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='measurement_date_idx')],
            },
        ),
    ]
