# Generated by Django 5.0.2 on 2024-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
        ('metrics', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['sensor'], name='measurement_sensor_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['machine', 'date'], name='measurement_machine_date_idx'),
        ),
    ]
