# Generated by Django 5.0.2 on 2024-02-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
        ('metrics', '0002_alter_measurement_date_and_more'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_sensor_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_machine_date_idx',
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['sensor', 'date'], name='measurement_machine_date_idx'),
        ),
    ]
